### ISSUE TITLE
ICS export is broken; UID's constantly change. (And add Sequence)

### ISSUE THREAD

**Issue by jarofgreen** [paviliondev/discourse-events#51] opened 2019-05-20 11:53 UTC
A forum I'm on has just added this plugin, but there is a problem. Every time I hit refresh on https://community.coops.tech/calendar.ics?time_zone=Europe/London the events have a different UID!

This totally breaks things for any system that tries to import the same feed twice, and use the UID to tie data objects together. It's definetly not how an ID is meant to work.

Also, check section 3.8.4.7 of https://tools.ietf.org/html/rfc5545 - note the bit about how many people use @ notation to make unique ID's. The example they give is

           UID:19960401T080045Z-4000F192713-0052@example.com

Can I hazard a guess - you were having problems where an event updated on the site but feed readers did not update it? So you make random UID's to force them to update it? 

The real solution you are looking for is the SEQUENCE property. This should be set on each event, and be updated appropriately. See section 3.8.7.4 of the RFC. This should just be an integer - it doesn't have to go up by one each time, as long as it's an integer which stays the same when there are no changes and goes up by some amount when there are changes, that's great. On one system I did I just took the timestamp of the last updated value for a record and used that as the sequence and it seems fine.

Thanks - the feed at the moment from this plugin can't really be said to be valid ICS, so this is important to fix.

**Comment by angusmcleod** [comment] 2019-05-21 23:05
Thanks for this, and for the insight here. If you have time to make a PR to this effect it would be much appreciated! I won't be able to get to it for at least a couple of weeks.

**Comment by jarofgreen** [comment] 2019-05-22 06:15
Unfortunately the last time I did Ruby was when Rails 2 was still new and shiny, so I don't think I'm any good. If I can do anything to encourage others I will tho. Thank you.

**Comment by md-misko** [comment] 2019-09-05 18:43
I was facing the same issue, hope this PR fixes it :-)

https://github.com/paviliondev/discourse-events/pull/62

**Comment by fzngagan** [comment] 2019-09-15 16:17
@md-misko 
I've thought of a simple workaround here. The uid generated when the event was first created will be its uid permanently. I've started working on it.

**Comment by fzngagan** [comment] 2019-09-16 03:27
@md-misko . I've started to look into this one. You'll be seeing a fix shortly.

**Comment by fzngagan** [comment] 2019-09-17 04:11
@md-misko 
This is the dev branch for the feature.
https://github.com/fzngagan/discourse-events/tree/add-uid-to-events

I've tested it and it works fine. Please test it and let us know if it solves the issue for you.

**Comment by md-misko** [comment] 2019-09-17 06:59
@fzngagan 
The UID is exported to webcal for newly created events (will test if it stays fixed today and tomorrow), but UID is now missing completely for existing events.

I believe this is the cause (UID is added only on create):
`DiscourseEvent.on(:post_created) do |post, opts, user|`

Perhaps there should be a one-time check (post plugin install/update) for all events without an UID?

**Comment by fzngagan** [comment] 2019-09-17 10:58
I'm thinking about what's the best way to do it. Any suggestions @angusmcleod

**Comment by angusmcleod** [comment] 2019-09-18 00:21
@fzngagan Sorry, maybe I wasn't clear in our discussion, but I don't think we need to store the UID. As suggested in [here](https://tools.ietf.org/html/rfc5545#section-3.8.4.7) (and in those other docs we discussed), the UI should be

> the domain name or a domain literal IP address of the host on which the identifier was created on the right-hand side of an "@", and on the left-hand side, put a combination of the current calendar date and time of day (i.e., formatted in as a DATE-TIME value) along with some other currently unique (perhaps sequential) identifier available on the system (for example, a process id number)

We don't need to store a new value to achieve this. In our context a UID will be something like:

```
event_start:post_id@thepavilion.io
```

**Comment by fzngagan** [comment] 2019-09-18 01:26
> We don't need to store a new value to achieve this. In our context a UID will be something like:
> 
> ```
> event_start:post_id@site_domain
> ```

Yeah, that makes a lot more sense. I was inspired by the `icalendar`'s own UUID implementation but that would force us to save the UUID which is unnecessary in our case.

Thanks for the tip @angusmcleod

**Comment by md-misko** [comment] 2019-09-18 07:02
> I don't think we need to store the UID. As suggested in here (and in those other docs we discussed), the UID should be
>
>> the domain name or a domain literal IP address of the host on which the identifier was created on the right-hand side of an "@", and on the left-hand side, put a combination of the current calendar date and time of day (i.e., formatted in as a DATE-TIME value) along with some other currently unique (perhaps sequential) identifier available on the system (for example, a process id number)

@angusmcleod, I believe you are quoting [rfc5545](https://tools.ietf.org/html/rfc5545#section-3.8.4.7), which was superseded by [rfc7986](https://tools.ietf.org/html/rfc7986#section-5.3) which explicitly states:
> The description of the "UID" property in [RFC5545] contains some
   recommendations on how the value can be constructed.  In particular,
   it suggests use of host names, IP addresses, and domain names to
   construct the value.  However, this is no longer considered good
   practice, particularly from a security and privacy standpoint, since
   use of such values can leak key information about a calendar user or
   their client and network environment.  This specification updates
   [RFC5545] by stating that "UID" values MUST NOT include any data that
   might identify a user, host, domain, or any other security- or
   privacy-sensitive information.  It is RECOMMENDED that calendar user
   agents now generate "UID" values that are hex-encoded random
   Universally Unique Identifier (UUID) values as defined in
   Sections 4.4 and 4.5 of [RFC4122].

Personally, I would be quite happy with the following implementation

`post_id@site_domain`

which only "leaks" domain name, which is inevitably exposed in the webcal link itself, so I don't see any security implications here.

The most important issue to consider here is **not** including `event_start` as part of the UID, since event start can change and this approach generates new UID on such change.

My first proposal was to use event (=post) url as UID (since post ID is guaranteed to be unique within Discourse instance), but the slug part of the url can also change.

Now I believe the easiest way to solve this, without storing the UID in a separate field, is to use `uid: post_id@site_domain` coupled with `sequence: version_of_first_post` to uniquely identify the event and any subsequent changes to its details.

I have already tested this approach (using url as UID) and it works perfectly both with rescheduling and changing event details.

**Comment by jarofgreen** [comment] 2019-09-18 07:52
> The most important issue to consider here is not including event_start as part of the UID, since event start can change and this approach generates new UID on such change.

Just posting to back this up, and to apologise for quoting the wrong RFC to start with - I did know there are 2 versions, but I got the wrong one :man_facepalming:

**Comment by fzngagan** [comment] 2019-09-18 14:42
Thanks for your notes guys.

**Comment by angusmcleod** [comment] 2019-09-20 06:29
@md-misko Interesting, thanks for your insight.

I'm wondering if using just ``post_id@domain`` would cause an issue when we launch the [recurring events feature]https://thepavilion.io/t/events-recurring-and-or-multiple-events/841). As you can see in the linked topic, the way we're thinking of doing this is by updating the same topic with each successive event datetime. This is also poses an issue with just using the topic url.

On your other suggestion:

> Now I believe the easiest way to solve this, without storing the UID in a separate field, is to use uid: post_id@site_domain coupled with sequence: version_of_first_post to uniquely identify the event and any subsequent changes to its details.

I like this approach. Looking at this thread again, the other thing that struck me is that we should really be using ``topic_id@domain`` as events in this plugin are tied to topics, not posts.

One question for me here is whether every increment of post.version is a "significant revision" to warrant an increment in the [Sequence Number](https://tools.ietf.org/html/rfc5545#section-3.8.7.4). 

Given both the question around the use of post.version, and the need to handle recurring events within the same topic, I think we may need to store a seperate ``sequence`` property for each event, which we increment whenever key event details are changed, such as times. We'll also need to add a recurrence property to represent events in a series.

So something like:

```
uid: topic_id/series_id@site_domain, sequence: event_sequence
```

@md-misko @jarofgreen thoughts?

**Comment by jarofgreen** [comment] 2019-09-20 06:57
So the ICAL format already had fields built in to handle recurring events.
You can have one EVENT block and specify any recursion options you want in
that.

I don't know what you have done for recursive events, but provided you can
fit into that maybe it's all fine and that shouldn't cause any problems for
the UID?

I'm on my phone now but I'll try and look up details later.

Also - recursive events are THE WORST. Good luck 😀

James

**Comment by md-misko** [comment] 2019-09-20 10:29
@angusmcleod

> I like this approach. Looking at this thread again, the other thing that struck me is that we should really be using topic_id@domain as events in this plugin are tied to topics, not posts.

> So something like:
>
> `uid: topic_id/series_id@site_domain, sequence: event_sequence`

Absolutely agree, I always had `topic_id` in mind where `post_id` was written.

I've put the following changes in my fork https://github.com/md-misko/discourse-events.git if anyone wishes to test it (I'm using this on my production site, because I have an external process that **really** depends on the uniqueness of the UIDs).

```
            # event UID (combination of topic id and domain name is unique)
            e.uid = "#{t.id}@" << SiteSetting.notification_email.split('@')[1]

            # increment event sequence number each time the first post of the topic is changed
            e.sequence = t.posts.first.version
```

> One question for me here is whether every increment of post.version is a "significant revision" to warrant an increment in the Sequence Number. A post version increment in Discourse includes every change to the post, some of which are not strictly relevant to the event.

Only changes to the first post in the topic are incremented, and this can happen for various reasons:
- event description change (topic title) 
- tagging of events (add or remove)
- change of venue (location plugin)
- event start/end change (event plugin)
- event details change (first post body)
- future unknown actions

There are so many variables here it would be difficult to maintain a fixed set so I would opt to log them all (usually there are not that many changes applied to the event type topic anyway).

My approach is to increment ics sequence number at every revision and let the calendar client deal with it (this is what revision field is for). The important thing is that none of the changes described above modifies the UID of the event itself.

I would also strongly support what @jarofgreen said about recurring events (at least for the ics export part): ics has fields to designate recurrence and it would be unwise to combine any recurrence part with the uid field (as recurrence can also be changed/removed from the event afterwards).

**Comment by angusmcleod** [comment] 2019-09-20 12:34
> There are so many variables here it would be difficult to maintain a fixed set

Keep in mind the ``sequence`` property is only relevant to the event properties sent via the iCalendar feed, i.e.

- event start
- event end
- event timezone
- topic title

Moreover, I'm not sure ``topic title`` counts as a "significant change" worthy of an increment, so we're just really talking about changes to the time and timezone, which is relatively easy to track with a seperate counter in the ``PostRevisor``.

If we map it to the post.version, it'll change in many circumstances in which those properties (i.e. event start, end and timezone) remain the same, some of which you've listed above.

Also, the squence property is used for other purposes such as event RSVP. If we increment it for every single edit and tweak to the topic and first post data, this could complicate that behaviour.

After delving into recurrence earlier today, I'm satisfied we can handle that through the RRULE and RDATE properties. So yes no need for a recurrence_id :+1:

**Comment by fzngagan** [comment] 2019-09-20 15:27
Its a really insightful conversation here. I'll summarize the points raised here and course of action IMHO.

1. Using topic_id in the uid.(As we can consider the recurring event as a single event with RRULE and RDATE properties as @angusmcleod  suggested).
2. Using PostRevisor with only event-related properties kind of custom `event revision` which will be incremented on event-related property change.




@angusmcleod , @md-misko , @jarofgreen thoughts?

**Comment by jarofgreen** [comment] 2019-09-23 19:29
> Moreover, I'm not sure topic title counts as a "significant change" worthy of an increment,

I would disagree - remember if it's not included, some popular calendar software (Google) won't update your event unless the sequence increases too. So you'll get a bug report; "I changed the topic title on the site fine but Google still shows me the old one". I think anything that goes in the feed should change the sequence.

> Also, the squence property is used for other purposes such as event RSVP. If we increment it for every single edit and tweak to the topic and first post data, this could complicate that behaviour.

This is interesting and I'm not fully aware of interactions here; but I think a change to the title could be a significant change that might affect someones RSVP status? 

(Sorry I haven't had time to look into this more; thanks for all your care on this!)

**Comment by md-misko** [comment] 2019-09-23 21:22
[Component Revisions](https://tools.ietf.org/html/rfc5546#section-2.1.4) section of rfc5546 describes sufficient conditions which require sequence number increase. It also states:

> In addition, changes made by the "Organizer" to other properties MAY also require the sequence number to be incremented.  The "Organizer" CUA MUST increment the sequence number whenever it makes changes to properties in the calendar component that the "Organizer" deems will jeopardize the validity of the participation status of the "Attendees".  For example, changing the location of a meeting from one location to another distant location could effectively impact the participation status of the "Attendees".

and:

> Whilst a change in sequence number is indicative of a significant change to a previously scheduled item, "Attendee" CUAs SHOULD NOT rely solely on a change in sequence number as a means of detecting a significant change.  Instead, CUAs SHOULD compare the old and new versions of the calendar components, determine the exact nature of the changes, and make decisions -- possibly based on "Calendar User" preferences -- as to whether the user needs to be explicitly informed of the change.

**Comment by angusmcleod** [comment] 2019-09-30 06:11
@jarofgreen @md-misko Thanks guys, very useful.

> So you'll get a bug report; "I changed the topic title on the site fine but Google still shows me the old one". I think anything that goes in the feed should change the sequence.

As far as I understand, the sequence is not used to determine whether or not to update the details themselves, it is use to determine things like whether or not a user should be notified. The details of the event are updated each time the ical feed is polled. But if I'm wrong in this I'm happy to add in the title as well.

@fzngagan Here's what we're going to do:

1. Create a new property: ``event_version``. Increment it whenever these properties are changed:

  - event_start
  - event_end
  - event_timezone

event_start and event_end are the only properties which [RFC5546 s2.1.4](https://tools.ietf.org/html/rfc5546#section-2.1.4) lists as requiring a sequence increment, which relate to properties in our system. I think it's also prudent to change it on a timezone change. 

We seperately make a change to the locations plugin to increment event_version when the location changes. That's a matter for the locations plugin.

When we add event recurrence we'll also add event_series_period as a property that triggers a version increment.

**Comment by fzngagan** [comment] 2019-09-30 06:22
Yes, Thanks for the clarification. I'll start working on this now.

**Comment by jarofgreen** [comment] 2019-09-30 06:39
> The details of the event are updated each time the ical feed is polled.

I haven't tested Google Calendar fully for years, but last time I tested it that's not what Google Calendar does. It needs an change to SEQUENCE or it won't pick up any changes to the event.

Remember this whole issue started because the plugin is sending random UID's, which I bet was to get around this :-)

However, in the spirit of incremental improvements, this is really good. It gives us stable UID's and a sequence property that starts being useful. If we need to tweak later which changes do or don't cause event_version to be incremented, that sounds like a minor thing.

So thanks for looking at this.

(BTW Testing Google Calendar is pretty easy to do - hand create a ICAL file, serve it on a static URL somewhere, import to Google Calendar by URL, edit the ICAL file, wait 24 hours and see what changes do or don't make it into Google Calendar.)

**Comment by fzngagan** [comment] 2019-09-30 06:42
@jarofgreen . The reason random UIDs were being generated wasn't intentional. Its how the iCalendar gem functions when a UID isn't passed explicitly.

**Comment by fzngagan** [comment] 2019-10-02 05:28
We've started a topic on our Discourse for this discussion. You guys can follow it here.
https://thepavilion.io/t/event-uid-changes-on-webcal-export-and-add-sequence-number/1802

**Closed** 2019-10-09 05:33 UTC
